/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.equipo10.restaurante;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author 54266
 */
public class Mesas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mesas
     */
   
    private JFrame frame;
    private JPanel panelMesas;
    private int numeroMesa = 1;

    public Mesas() {
        frame = new JFrame("Gestión de Mesas");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 400);
        JPanel panelBotonAgregarMesa = new JPanel(); // para el boton de agregar solo 
        JButton agregarMesaButton = new JButton("Agregar Mesa");
        panelBotonAgregarMesa.add(agregarMesaButton);
        
        panelMesas = new JPanel(new GridLayout(0, 3));
        
        
        frame.add(panelBotonAgregarMesa, BorderLayout.NORTH);
        frame.add(panelMesas, BorderLayout.CENTER);

        
        

        agregarMesaButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                agregarMesa();
            }
        });

        frame.setLayout(new FlowLayout());
        frame.setVisible(true);
    }

    private void agregarMesa() {
        JButton mesaButton = new JButton("Mesa " + numeroMesa);
         mesaButton.setBackground(Color.red);
   /*     mesaButton.addActionListener(new ActionListener(){
        
        public void actionPerformed(ActionEvent e) {
                // Lógica específica para esta mesa cuando se hace clic en ella
                JOptionPane.showMessageDialog(null, mesaButton.getText() + " seleccionada");
            }
        
        }  );*/
        mesaButton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    if(mesaButton.getBackground().equals(Color.green)){//abierta
                    // Cambia el color del botón a rojo
                    mesaButton.setBackground(Color.red);
                     JOptionPane.showMessageDialog(null, mesaButton.getText() + " mesa cerrada");
                }else{ mesaButton.setBackground(Color.green);
                     JOptionPane.showMessageDialog(null, mesaButton.getText() + " mesa abierta");}
            }}
        });
        
        panelMesas.add(mesaButton);
        frame.revalidate();
        frame.repaint();
        numeroMesa++;
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new Mesas();
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}