/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo10.restaurante.Vistas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Facua
 */
public class Principal extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    private ImageIcon iconoMesaVerde = new ImageIcon(getClass().getResource("/img/mesa_verde.png"));
    private ImageIcon iconoMesaRoja = new ImageIcon(getClass().getResource("/img/mesa_roja.png"));
    private List<JLabel> lista = new ArrayList<>();

    public Principal() {
        initComponents();
        listarMesas();
        clickParaCambiar();
        IconoEsquina.setIcon(escaladoIcon(25, 25, "/img/app_icon.png"));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPpantalla = new javax.swing.JPanel();
        mesa4 = new javax.swing.JLabel();
        mesa2 = new javax.swing.JLabel();
        mesa6 = new javax.swing.JLabel();
        mesa3 = new javax.swing.JLabel();
        mesa5 = new javax.swing.JLabel();
        mesa1 = new javax.swing.JLabel();
        mesa9 = new javax.swing.JLabel();
        mesa8 = new javax.swing.JLabel();
        mesa7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLminimizar = new javax.swing.JLabel();
        jLexit = new javax.swing.JLabel();
        IconoEsquina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 520));

        jPpantalla.setBackground(new java.awt.Color(153, 255, 153));
        jPpantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mesa4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        mesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        mesa6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        mesa3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        mesa5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        mesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        mesa9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        mesa8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        mesa7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa_verde.png"))); // NOI18N
        mesa7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpantalla.add(mesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        getContentPane().add(jPpantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 670, 520));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLminimizar.setBackground(new java.awt.Color(0, 0, 0));
        jLminimizar.setForeground(new java.awt.Color(0, 0, 0));
        jLminimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        jLminimizar.setOpaque(true);
        jLminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLminimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLminimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLminimizarMouseExited(evt);
            }
        });
        jPanel2.add(jLminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 30));

        jLexit.setBackground(new java.awt.Color(0, 0, 0));
        jLexit.setForeground(new java.awt.Color(0, 0, 0));
        jLexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jLexit.setOpaque(true);
        jLexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLexitMouseExited(evt);
            }
        });
        jPanel2.add(jLexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 40, 30));
        jPanel2.add(IconoEsquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitMouseClicked
        int jop = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la pestaña?", "Salir", jop);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLexitMouseClicked

    private void jLminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLminimizarMouseClicked
        this.setState(Principal.ICONIFIED);
    }//GEN-LAST:event_jLminimizarMouseClicked

    private void jLexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitMouseEntered
        jLexit.setBackground(Color.red);
    }//GEN-LAST:event_jLexitMouseEntered

    private void jLexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitMouseExited
        jLexit.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLexitMouseExited

    private void jLminimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLminimizarMouseEntered
        jLminimizar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLminimizarMouseEntered

    private void jLminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLminimizarMouseExited
        jLminimizar.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLminimizarMouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoEsquina;
    private javax.swing.JLabel jLexit;
    private javax.swing.JLabel jLminimizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPpantalla;
    private javax.swing.JLabel mesa1;
    private javax.swing.JLabel mesa2;
    private javax.swing.JLabel mesa3;
    private javax.swing.JLabel mesa4;
    private javax.swing.JLabel mesa5;
    private javax.swing.JLabel mesa6;
    private javax.swing.JLabel mesa7;
    private javax.swing.JLabel mesa8;
    private javax.swing.JLabel mesa9;
    // End of variables declaration//GEN-END:variables

    private void listarMesas() {
        lista.add(mesa1);
        lista.add(mesa2);
        lista.add(mesa3);
        lista.add(mesa4);
        lista.add(mesa5);
        lista.add(mesa6);
        lista.add(mesa7);
        lista.add(mesa8);
        lista.add(mesa9);
    }

    private ImageIcon escaladoIcon(int largo, int alto, String url) {
        //imagen origen
        Image img = new ImageIcon(getClass().getResource(url)).getImage();
        //escala imagen
        Image newimg = img.getScaledInstance(largo, alto, java.awt.Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newimg);
        //asigna a componenente JLabel
        return imageIcon;
    }

    private boolean esMesaVerde(JLabel label) {
        ImageIcon iconoActual = (ImageIcon) label.getIcon();
        if (iconoActual != null) {
            return iconoActual.getDescription().equals(iconoMesaVerde.getDescription());
        }
        return false;
    }

    private void cambioDeColorMesa(JLabel label) {
        int x = label.getX();
        int y = label.getY();
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent evt) {

                label.setSize(label.getWidth() + 6, label.getHeight() + 6);
            }

            @Override
            public void mouseExited(MouseEvent evt) {

                label.setLocation(x, y);
                label.setSize(label.getWidth() - 6, label.getHeight() - 6);
            }

            @Override
            public void mouseClicked(MouseEvent evt) {
                if (esMesaVerde(label)) {

                    label.setIcon(iconoMesaRoja);
                } else {
                    label.setIcon(iconoMesaVerde);
                }
            }
        });
    }

    private void clickParaCambiar() {

        for (JLabel todo : lista) {

            cambioDeColorMesa(todo);
        }
    }
}
